// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jTZZpZX8pZkcBvaqBi3TT7wYtrabp7E',
    appId: '1:47784141917:web:2468ab918387062c03d9b4',
    messagingSenderId: '47784141917',
    projectId: 'tourify-a3777',
    authDomain: 'tourify-a3777.firebaseapp.com',
    storageBucket: 'tourify-a3777.firebasestorage.app',
    measurementId: 'G-XX7M3MQMT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_tNVdlrOy4FQ47DbO14v7EQGbdvikhY',
    appId: '1:47784141917:android:17fc56c591a1a76903d9b4',
    messagingSenderId: '47784141917',
    projectId: 'tourify-a3777',
    storageBucket: 'tourify-a3777.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-0mjncyY5h5El4rniIJ6avyJQKMGAnw',
    appId: '1:47784141917:ios:eba064dad46667aa03d9b4',
    messagingSenderId: '47784141917',
    projectId: 'tourify-a3777',
    storageBucket: 'tourify-a3777.firebasestorage.app',
    iosBundleId: 'com.example.tourify',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-0mjncyY5h5El4rniIJ6avyJQKMGAnw',
    appId: '1:47784141917:ios:eba064dad46667aa03d9b4',
    messagingSenderId: '47784141917',
    projectId: 'tourify-a3777',
    storageBucket: 'tourify-a3777.firebasestorage.app',
    iosBundleId: 'com.example.tourify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-jTZZpZX8pZkcBvaqBi3TT7wYtrabp7E',
    appId: '1:47784141917:web:3a6f62f2cca5ae1b03d9b4',
    messagingSenderId: '47784141917',
    projectId: 'tourify-a3777',
    authDomain: 'tourify-a3777.firebaseapp.com',
    storageBucket: 'tourify-a3777.firebasestorage.app',
    measurementId: 'G-L0DRMKX2GW',
  );
}
